# Generated by Django 4.0.4 on 2022-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
